# Generated by Django 5.1.3 on 2024-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Study_name', models.CharField(max_length=50)),
                ('Study_Phase', models.CharField(max_length=50)),
                ('Sponsor_Name', models.CharField(max_length=50)),
                ('Study_Description', models.TextField()),
            ],
        ),
    ]
