# Generated by Django 5.1.3 on 2024-11-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_study',
            new_name='createstudy',
        ),
    ]
